<hr><h1 style=text-align:center>Naukri.Com Analysis Of India<hr>

<img src="https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/jobs-660_031819053533.jpg" alt="alternatetext">

<hr><h2 style=text-align:center>Introduction</h2><hr>
<h3>&#8226; Getting a first job is an important rite of passage in many cultures. The youth may start by doing household work, odd jobs, or working for a family business. </h3>
<h3>&#8226; naukri.com is a recruitment platform that provides hiring-related services to corporates/recruiters, placement agencies and to job seekers in India.</h3>
<h3>&#8226; The data set captures the 14 attributes of the job postings that are done between 2015 - 2017</h3>
<h3>&#8226;This is naukri.com job portal dataset and it was created by teams at PromptCloud and DataStock. The dataset gives you information about job opportunities published by recruiters and has some importand features or columns such as Industry, Location, Payrate, Experience required in Years etc which can be analysed.</h3>

<hr><h2 style=text-align:center>Dataset Link</h2><hr>
<h3><a href="https://www.kaggle.com/PromptCloudHQ/jobs-on-naukricom">https://www.kaggle.com/PromptCloudHQ/jobs-on-naukricom</a><br>
<br>
<h3>Click download button to download this dataset &nbsp;
<button class="btn"><a href="https://www.kaggle.com/PromptCloudHQ/jobs-on-naukricom/download"><i class="fa fa-download"></i>Download</a>


<hr><h2 style=text-align:center>Problem Statement</h2></hr>
<h3> Anticipate job market demand, ( forecast)</h3>
<h2 style=text-align:center>Solution</h2>
<h3> Lets tackle this problem ,i.e forecasting the job market demand by analysis of job market analysis of india.</h3>

<hr><h2 style=text-align:center>Import Libraries<hr>

In [ ]:
import numpy as np #for algebric calculations
import pandas as pd #essential for data reading,writing etc
import seaborn as sns #visualization library
import plotly.express as px #ploting parameter's
import plotly.express
import matplotlib #visualization library.
import matplotlib.pyplot as plt #visualization library.
import sys #for System-specific parameters and functions.
%matplotlib inline
plt.rcParams['figure.figsize'] = (10, 7) #plotting parameters size's.
import warnings
warnings.filterwarnings('ignore')

# display the version of import libraries

print('Python : {}'.format(sys.version[0:5]))
print('Numpy : {}'.format(np.__version__))
print('Pandas : {}'.format(pd.__version__))
print('Matplotlib : {}'.format(matplotlib.__version__))
print('Seaborn : {}'.format(sns.__version__))
print('Plotly.Express : {}'.format(plotly.__version__))

<hr><h2 style=text-align:center>Import Dataset<hr>

In [ ]:
# Define the path of CSV file & import the dataset.

df=pd.read_csv('../input/jobs-on-naukricom/naukri_com-job_sample.csv')

In [ ]:
# Display the first 10 columns.

df.head(5)

<div class="text_cell_render border-box-sizing rendered_html">
<p>Let's take a look at the variable descriptions:</p>
<h2  style=text-align:center>Features</h2>
<table style="width:90%; border: 2px solid blue">
    <thead>
        <tr> 
            <th><mark>Variable</mark></th>
            <th><mark>Type</mark></th>
            <th><mark>Scale</mark></th>
            <th><mark>Description</mark></th>
        </tr>
    </thead>
        <tbody>
        <tr>
            <td>Company</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The name of the company.</td>
        </tr>
         <tr>
            <td>Education</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The education of the candidate.</td>
        </tr>
         <tr>
            <td>Experience</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The experience that is needed by the candidates.</td>
        </tr>
         <tr>
            <td>Industry</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The industry the job is posted for.</td>
        </tr>
         <tr>
            <td>Job Discription</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The job description.</td>
        </tr>
         <tr>
            <td>Job ID</td>
            <td>Qualitative,<br> Discrete (int64)</td>
            <td>Nominal</td>
            <td>The Job ID given by the website.</td>
        </tr>
         <tr>
            <td>Joblocation_address</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The location of the job.</td>
        </tr>
         <tr>
            <td>Job Title</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The title of the job.</td>
        </tr>
         <tr>
            <td>Number of Position</td>
            <td>Quantitative,<br> Discrete (Float64)</td>
            <td>Nominal</td>
            <td>The number of positions available.</td>
        </tr>
         <tr>
            <td>Payrate</td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The rate of payment of the jobs.</td>
        </tr>
         <tr>
            <td>Post Date</td>
            <td>Ordinal,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The date when the job was posted.</td>
        </tr>
         <tr>
            <td>Site Name </td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The name of the site.</td>
        </tr>
         <tr>
            <td>Skills </td>
            <td>Qualitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The skills that are required.</td>
        </tr>
         <tr>
            <td>Unique ID </td>
            <td>Quantitative,<br> Discrete (Boolean)</td>
            <td>Nominal</td>
            <td>The unique ID given by the website.</td>
        </tr>
        </tbody>            
</table>
<p><strong>Quantitative :- Numerical</strong><br>
<strong>Qualitative :- Categorical</strong></p>

</div>

In [ ]:
# Display the number of rows and columns in the dataset.

nrow,ncol=df.shape
print(f'There are {nrow} rows and {ncol} colunms in the dataset')

In [ ]:
#The total number of elements.
#This is equal to the row_count * column_coun.

print(df.shape[0] * df.shape[1])

In [ ]:
# Display the information about DataFrame including the index dtype, columns and etc.  

df.info()

In [ ]:
count_missing = df.isnull().sum()
percent_missing =  count_missing* 100 / df.shape[0]
missing_value_df = pd.DataFrame({'count_missing': count_missing,
                                 'percent_missing': percent_missing})

missing_value_df.style.background_gradient(cmap='Spectral')

In [ ]:
unique_df = pd.DataFrame([[df[i].nunique(), df[i].unique()]for i in df.columns],
                         columns=['Count','unique'],
                         index=df.columns)
unique_df.style.background_gradient(cmap='magma')

<hr><h2 style=text-align:center>Data Cleaning Processing<hr>

## Payrate Spliting Processing

In [ ]:
# split method to split payrate min to max

pay_split = df['payrate'].str[0:-1].str.split('-', expand=True)
pay_split.head(10)

In [ ]:
#remove space in left and right
pay_split[0] =  pay_split[0].str.strip()

#remove comma 
pay_split[0] = pay_split[0].str.replace(',', '')

#remove all character in two condition
# 1 remove if only character
# 2 if start in number remove after all character
pay_split[0] = pay_split[0].str.replace(r'\D.*', '')

#display 
pay_split[0].head(10)

In [ ]:
#remove space in left and right 
pay_split[1] =  pay_split[1].str.strip()

#remove comma 
pay_split[1] = pay_split[1].str.replace(',', '')

#remove all character in two condition
# 1 remove if only character
# 2 if start in number remove after all character
pay_split[1] = pay_split[1].str.replace(r'\D.*','')

#display 
pay_split[1].head(10)

In [ ]:
pay_split[0] = pd.to_numeric(pay_split[0], errors='coerce')
pay_split[1] = pd.to_numeric(pay_split[1], errors='coerce')

In [ ]:
pay=pd.concat([pay_split[0], pay_split[1]], axis=1, sort=False)

In [ ]:
# rename the columns into min payrate and max payrate.
pay.rename(columns={0:'min_pay', 1:'max_pay'}, inplace=True )
pay.head()

In [ ]:
# min and max payarte store the value in the dataframe.

df=pd.concat([df, pay], axis=1, sort=False)

In [ ]:
df.head(5)

## Experience Spliting Processing

In [ ]:
# spliting the experience into min experience to max experience.

experience_split = df['experience'].str[0:-1].str.split('-', expand=True)
experience_split.head()

In [ ]:
#remove space in left and right 
experience_split[0] =  experience_split[0].str.strip()

#remove comma 
experience_split[0] = experience_split[0].str.replace('yr', '')

#remove all character in two condition
# 1 remove if only character
# 2 if start in number remove after all character
experience_split[0] = experience_split[0].str.replace(r'yr', '')

#display 
experience_split[0].head()

In [ ]:
#remove space in left and right 
experience_split[1] =  experience_split[1].str.strip()

#remove comma 
experience_split[1] = experience_split[1].str.replace('yr', '')

#remove all character in two condition
# 1 remove if only character
# 2 if start in number remove after all character
experience_split[1] = experience_split[1].str.replace(r'yr', '')

#display 
experience_split[1].head()

In [ ]:
experience_split[0] = pd.to_numeric(experience_split[0], errors='coerce')
experience_split[1] = pd.to_numeric(experience_split[1], errors='coerce')

In [ ]:
experience=pd.concat([experience_split[0], experience_split[1]], axis=1, sort=False)

In [ ]:
# rename the cloumns to min and max experience

experience.rename(columns={0:'min_experience', 1:'max_experience'}, inplace=True)
experience.head()

In [ ]:
# store the min and max experience in the dataframe.

df=pd.concat([df, experience], axis=1, sort=False)

In [ ]:
#displat max and min experience

df.head(5)

## View Payrate and Experience Average

In [ ]:
# Display average payrate and average experience.
# min experience and max experience define the average experience.
# min payrate and max payrate define the average payrate.

df['avg_payrate']=(df['min_pay'].values + df['max_pay'].values)/2
df['avg_experience']=(df['min_experience'].values + df['max_experience'].values)/2
df.head(5)

## Feature Engineering Of Date Variable

In [ ]:
df['postdate'].dtypes

In [ ]:
# parse the dates, currently coded as strings, into datetime format

df['postdate'] = pd.to_datetime(df['postdate'])

In [ ]:
# extract year from date

df['Year'] = df['postdate'].dt.year
df['Year'].head(5)

In [ ]:
# extract month from date

df['Month'] = df['postdate'].dt.month
df['Month'].head(5)

In [ ]:
df['Month'].tail(5)

In [ ]:
# extract day from date

df['Day'] = df['postdate'].dt.day
df['Day'].head(5)

In [ ]:
df['Day'].tail(5)

In [ ]:
# drop the original Date variable

df.drop('postdate', axis=1, inplace = True)

In [ ]:
df.head(5)

# Location Spliting Processing

In [ ]:
df['joblocation_address'].value_counts().head(10)

In [ ]:
replacements = {
   'joblocation_address': {
      r'(Bengaluru/Bangalore)':'Bangalore',
      r'Bengaluru':'Bangalore',
      r'Bangalore':'Bangalore',
      r'Bangalore Bangalore':'Bangalore',
      r'Hyderabad/Secunderabad':'Hyderabad',
      r'Mumbai , Mumbai':'Mumbai',
      r'Noida': 'Delhi',
      r'Delhi': 'Delhi',
      r'Gurgaon': 'Delhi',
      r'Delhi/NCR(National Capital Region)':'Delhi',
      r'Delhi/NCR(National Capital Region) ':'Delhi',
      r' Delhi/NCR(National Capital Region) ':'Delhi',
      r' Delhi/NCR(National Capital Region)':'Delhi',
      r'DELHI(NATIONAL CAPITAL REGION)':'Delhi',
      r'Delhi,Delhi':'Delhi',
      r'Noida/Greater Noida':'Delhi',
      r'Ghaziabad': 'Delhi',
      r'Delhi/NCR(National Capital Region),Gurgaon':'Delhi',
      r'NCR,NCR': 'Delhi',
      r'Delhi/NCR':'Delhi', 
      r'Bangalore,Bangalore / Bangalore':'Bangalore',
      r'Bangalore,karnataka': 'Bangalore',
      r'Delhi NCR':'Delhi',
      r'Delhi':'Delhi',
   }
}
df.replace(replacements, regex=True, inplace=True)
joblocation_address = df['joblocation_address'].value_counts()

In [ ]:
# filter and find unique() cities from data set

df.joblocation_address = df.joblocation_address.str.upper()
new_location =df.joblocation_address.str.strip().str.split(",", expand = True)[0].str.split(" ", expand = True)[0].value_counts().reset_index()
new_location.columns = ["Location", "Job_Opportunities"]
new_location = new_location[:10]
new_location.style.background_gradient(cmap = "PuOr")

In [ ]:
# drop the original Date variable

df.drop('payrate', axis=1, inplace = True)

In [ ]:
# drop the original Date variable

df.drop('experience', axis=1, inplace = True)

In [ ]:
# drop the original Date variable

df.drop('uniq_id', axis=1, inplace = True)

In [ ]:
# a general overview of data
# T means Transpose

df.describe().T

In [ ]:
#Dataset Summary statistics - categorical variables

df.describe(include = ['object']).T

<hr><h2 style="text-align:center">Bivariate Analysis</h2><hr>

<hr><h2 style="text-align:center">Types of Variables</h2><hr>

<hr><h3 style="text-align:center">Categorical Variables&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Numerical Variables</h3><hr>

- ## Categorical Variables

In [ ]:
# find categorical variables

categorical = [var for var in df.columns if df[var].dtype=='O']
print('There are {} categorical variables\n'.format(len(categorical)))
print('The categorical variables are :\n', categorical)

In [ ]:
# view the categorical variables

df[categorical].head()

In [ ]:
count_missing = df[categorical].isnull().sum()
percent_missing =  count_missing* 100 / df.shape[0]
missing_value_df = pd.DataFrame({'count_missing': count_missing,
                                 'percent_missing': percent_missing})

missing_value_df.style.background_gradient(cmap='tab20b')

- ## Numerical Variables

In [ ]:
# find numerical variables

numerical = [var for var in df.columns if df[var].dtype!='O']
print('There are {} numerical variables\n'.format(len(numerical)))
print('The numerical variables are :', numerical)

In [ ]:
# view the numerical variables

df[numerical].head()

### Missing values in numerical variables

In [ ]:
# check missing values in numerical variables

count_missing = df[numerical].isnull().sum()
percent_missing =  count_missing* 100 / df.shape[0]
missing_value_df = pd.DataFrame({'count_missing': count_missing,
                                 'percent_missing': percent_missing})

missing_value_df.style.background_gradient(cmap='coolwarm')

### Outliers In Numerical Variables

In [ ]:
# view summary statistics in numerical variables

print(round(df[numerical].describe()))

### Correlation For Numerical Features

In [ ]:
cor_mat = df.corr()
fig, ax = plt.subplots(figsize=(15,10))
plt.title('Correlation Heatmap of Job Market Analysis of India')
sns.heatmap(cor_mat, ax=ax, annot=True,cmap="PuOr", center=0, linewidths=0.08,linecolor="magenta")
plt.show()

### Interpretation

#### From the above correlation, we can conclude that :-

- ####  Minimun Payrate and Average Payrate variables are highly positively correlated (correlation coefficient = 0.98).
- #### Minimum Experience and Minimun Payrate variables are also highly positively correlated (correlation coefficient = 0.71).

In [ ]:
plt.figure(figsize=(10,6))
corr = df.corr()["min_pay"]
corr.sort_values().head(20)[:-3].plot(kind='bar', color= ['olive','fuchsia',
                                                                'limegreen','grey','yellow','aqua',
                                                                'lawngreen','red',])
corr.abs().sort_values(ascending=False)[3:]

We can more clearly see that both <mark>min_experience</mark> and <mark>numberofpositions</mark> had the strongest linear correlations with <mark>min_pay</mark> target variable

<hr><h2 style=text-align:center>Company Based Analysis<hr>

In [ ]:
#display the company names..highest to lowest

com_Category = df.company.str.lstrip().str.rstrip().value_counts().reset_index()
com_Category.columns = ["Company", " Number of Company"]
com_Category = com_Category[:10]
com_Category.style.background_gradient(cmap = "tab20c")

In [ ]:
#pLot of companies

f,ax=plt.subplots(figsize=(17,7))
df['company'].value_counts().head(10).plot(kind = 'bar', color =['fuchsia','orange',
                                                                 'limegreen','yellow','grey','aqua',
                                                                 'lawngreen','deepskyblue','indigo','skyblue'])
plt.title('Bar Plot', fontsize=22)
plt.show()

<hr><h2 style=text-align:center>Industries Based Analysis<hr>

In [ ]:
# These data shows the biggest industry in the country.

ind_Category = df.industry.str.lstrip().str.rstrip().value_counts().reset_index()
ind_Category.columns = ["Industry", " Number of Industry"]
ind_Category = ind_Category[:10]
ind_Category.style.background_gradient(cmap = "Blues")

In [ ]:
# Plot of Industries.

f,ax=plt.subplots(figsize=(18,7))
explode =(0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2)
df['industry'].value_counts().head(10).plot(kind = 'pie', startangle=60, explode = explode,autopct='%1.1f%%')
plt.title('Pie Chart', fontsize=22)
plt.show()

#### Software Services biggest industry in India, So it have the highest job opportunity

<hr><h2 style=text-align:center>Jobtitle Analysis<hr>

In [ ]:
#diplay the jobtitle.

Category = df.jobtitle.str.lstrip().str.rstrip().value_counts().reset_index()
Category.columns = ["jobtitle", " Number of Jobtitle"]
Category = Category[:10]
Category.style.background_gradient(cmap = "Greens")

In [ ]:
#scatter plot for jobtitle.

fig=px.scatter(df['jobtitle'].value_counts().head(10))
fig.show()

#### Business Development and Software Engineer are the higest occurring jobtitle

<hr><h2 style=text-align:center>Skills Analysis<hr>

In [ ]:
# display the skills

# These data shows the biggest industry in the country.

skills_Category = df.skills.str.lstrip().str.rstrip().value_counts().reset_index()
skills_Category.columns = ["Skills", " Number of Skills"]
skills_Category = skills_Category[:10]
skills_Category.style.background_gradient(cmap = "hot")

In [ ]:
# horizontal plot of skills

f,ax=plt.subplots(figsize=(17,7))
df['skills'].value_counts().head(5).plot(kind = 'line', color = 'midnightblue')
plt.title(' Line Plot', fontsize=22)
plt.show()

#### IT Software - Application Programming is highly demanded skill

<hr><h2 style=text-align:center>Top City For JobLocation<hr>

In [ ]:
# filter and find unique() cities from data set

df_joblocation_address = df.joblocation_address.str.upper()
new_location =df.joblocation_address.str.strip().str.split(",", expand = True)[0].str.split(" ", expand = True)[0].value_counts().reset_index()
new_location.columns = ["Location", "Job_Opportunities"]
new_location = new_location[:10]
new_location.style.background_gradient(cmap = "PuOr")

In [ ]:
plt.figure(figsize = (17,7))
plt.bar(new_location.Location,new_location.Job_Opportunities,color = ['orange','fuchsia',
                                                                'limegreen','grey','yellow','aqua',
                                                                'lawngreen','deepskyblue','indigo','skyblue'])
plt.xlabel("Locations")
plt.ylabel("Job Opportunities")
plt.xticks(new_location.Location, rotation = "60")
plt.title("Bar Plot")
plt.show()

<hr><h2 style=text-align:center>Payrate Analysis<hr>

### Co-relation Between Minimum Experience and Minimum Payrate

In [ ]:
#display the relation between min exp. and min payrate.

f,ax=plt.subplots(figsize=(17,7))
sns.stripplot(x='min_experience', y='min_pay', data=df, jitter=False)
plt.title('Seaborn Stripplots', fontsize=22)
plt.show()

###  Co-relation Between Maximum Experience and Maximum Payrate

In [ ]:
#display the relation between max exp. and max payrate.

sns.catplot(x='max_experience', y='max_pay', data=df , kind="boxen" , width=0.4 ,aspect=3)
plt.title('Seaborn Catplots using Boxen', fontsize=22)
plt.show()

### Co-relation Between Average Experience And Average Payrate

In [ ]:
#display the relation between average exp. and average payrate.

f,ax=plt.subplots(figsize=(20,8))
sns.stripplot(x='avg_experience', y='avg_payrate', data=df, jitter=False, size=6)
plt.title('Seaborn Stripplots', fontsize=22)
plt.show()

### Relation Between Minimum, Maximum Experience And Minimum Payrate

In [ ]:
#display the relation between min, max exp. and min payarte.

sns.pairplot(df, size=7,aspect=1,
             x_vars=["min_experience","max_experience"],
             y_vars=["min_pay"], diag_kind="kde", 
             plot_kws=dict(s=50, edgecolor = 'darkgreen', color="aqua", linewidth=1.5),diag_kws=dict(shade=True))

### Relation Between Minimum , Maximum Experience And Maximum Payrate

In [ ]:
#display the relation between min, max exp. and max payrate.

sns.pairplot(df, 
             size=7, aspect=1, 
             x_vars=["min_experience","max_experience"],
             y_vars=["max_pay"],
             kind="reg")

### Comparsion  Between Maximum Payrates & Industries

In [ ]:
#display the max payrate and industries comparsion.

df[['max_pay','industry']].groupby(["industry"]).median().sort_values(by='max_pay',
                                                                        ascending=False).head(10).plot.bar(color='springgreen')
plt.title('Bar Plot', fontsize=22)
plt.show()

### Comparsion  Between Minimum Payrates & Industries

In [ ]:
#display the min payrate and industries comparsion.

df[['min_pay','industry']].groupby(["industry"]).median().sort_values(by='min_pay',
                                                                        ascending=False).head(10).plot.bar(color='magenta')
plt.title('Horizontal Bar Plot', fontsize=22)
plt.show()

### Comparsion Between Average Payrates & Skills

In [ ]:
#display the average payrate and skills comparsion.

df[['avg_payrate','skills']].groupby(["skills"]).median().sort_values(by='avg_payrate',
                                                                  ascending=False).head(10).plot.bar(color='skyblue')
plt.title('Bar Plot', fontsize=22)
plt.show()

### Comparsion Between Average Payrates & Jobtitles

In [ ]:
df[['avg_payrate','jobtitle']].groupby(["jobtitle"]).median().sort_values(by='avg_payrate',
                                                                        ascending=False).head(10).plot.bar(color='orange')
plt.title('Horizontal Bar Plot', fontsize=22)
plt.show()

### Display The Number Of Position On Minimum Payrate

In [ ]:
# Position are available in minimum payrate

plt.figure(figsize=(10, 5))
df['min_pay'].hist(rwidth=0.9, bins=15, color='aqua')
plt.title('Minimum payment')
plt.xlabel('Payment')
plt.ylabel('Position')
plt.show()

### Display The Number Of Position On Maximum Payrate

In [ ]:
# Position are available in maximum payrate
plt.figure(figsize=(10, 5))
df['max_pay'].hist(rwidth=0.8, bins=15, color='r')
plt.title('Maximum payment')
plt.xlabel('Payment')
plt.ylabel('Position')

plt.show()

### Display The Available Position In The Industry

In [ ]:
# Number of position are available in the industry.

max_positions = df.loc[df.numberofpositions > 100].loc[:,['numberofpositions','industry']]
plt.figure(figsize=(15, 5))
explode =(0.1,0.12,0.2,0.1,0.2,0.05,0.1,0.3,0.5,1)
hist_position_value = pd.value_counts(max_positions.industry)
hist_position_value.index
hist_position_value[hist_position_value >1].plot(kind='pie',startangle=40,explode=explode, autopct='%1.1f%%')
plt.title('Pie Chart', fontsize=22)
plt.show()

<hr><h2 style=text-align:center>Conclusion</h2></hr>
<p><b>In short, according to given data, Most of the jobs on Naukri.com are related IT and software industry which are hiring for programming and design role category and Most of the job recruiters are from Bengeluru region.</b></p>
<p><b>The Information Technology & Information Technology Enabled Services (IT-ITeS) sector has rapid evolution and is changing the shape of Indian business/technology standards. It includes software development, consultancies, software management, online services and business process outsourcing (BPO).</b></p>
<p><b>And According data, analysis that information technology and Software service industry are most valuable indsutry in the country</b></p>
<p><b> We analysis that the management skills is the most highly offered salary in the industry</b></p>